### PR TITLE
Update types to include behavior data link and added this type to Fra…

### PR DESCRIPTION
**Pull request by ArcanePariah**
First time pull request, yippee!

Added new GameLink type and added it to one of the behavior frames.

### CODE REVIEW

**Comment by Talv** [comment]
Thanks for taking the effort, but I cannot take it as is for two reasons.

Firstly, `Behavior` on `CUnitStatusBehaviorAnim` technically is not a property. It cannot be bound, changed, or interacted by any other means. Once the frame is instantiated. I'm not sure why Blizzard have done it this way (since if they wanted to be immutable they could just flag it as readonly). But I have to follow their conventions.

For that reason I've implemented the same concept of `Desc` structures they have in SC2. Those could be kinda compared to traits or decorators.. it is just a way of extending underyling frame type with additional fields, without actually exposing them to a usual property interface.

That frame type is decorated by `CUnitStatusBehaviorDesc`, as specifid in:

https://github.com/Talv/sc2-layouts/blob/ac90cd0ce54090cb79a38753bd29b034ec952405/schema/frame_type.xml#L748

And that particular Desc includes `Behavior` as an field/element:

https://github.com/Talv/sc2-layouts/blob/ac90cd0ce54090cb79a38753bd29b034ec952405/schema/struct.xml#L145-L151

So if anything, the type should be altered here. Even though there's no extra support at all for `GameLink` types - no validation/code completions. But it might be useful for the future.

Second problem is that you've fogotten about `/`, and these newly added elements aren't terminated :P

**Comment by ArcanePariah** [comment]
Hehe, understandable. Was mostly seeing how to use VSCode + github pull requests becase I've never done them myself before (despite taking tons of them in).

So I'll correct the termination, easy enough.

Interesting the Behavior is not a property, just a decoration. So yes, I'll remove my addition to BehaviorAnim, but that actually suggests that if I add the gamelink support to the BehaviorDesc, it will work for ANY frame that uses that Desc, which is quite a few, and this can serve as a generic template for any gamelink type.

**Comment by ArcanePariah** [comment]
So in short, yes, I think I need to step back and consider the design of game link validation. I may start with the simple hardcoded case, and then include data space case later.

**Comment by Talv** [comment]
> but that actually suggests that if I add the gamelink support to the BehaviorDesc, it will work for ANY frame that uses that Desc, which is quite a few, and this can serve as a generic template for any gamelink type.

Yeah, exactly. In general this schema was laid out as closely as possible to the way it is in SC2, so there's no repetitions of the same fields/properties.

And sure take your time regarding gamedata parser. There are no fundamental code for getting it all to work, so you'll have to come up with it, if you still hold the interest ;) But yeah - any simple way is fine. In fact current support of `GameStrings` etc. is done a bit ugly :P Can always redesign it properly in the future.

**Pull request closed without merging**
